In [46]:
import requests
import pandas as pd
import os

In [52]:
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=20200201&stockNo=2330'
data = pd.read_html(requests.get(url).text)[0]
data.columns = data.columns.droplevel(0)
# data.columns = data.columns(['Date', 'Volume', '成交金額', 'Open', 'High', 'Low', 'Close', '漲跌價差','成交筆數'])
data = data.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})
path = os.path.join('./price_data', 'price_2330_20200201.csv')
print(path)
data.to_csv(path, index=False)

./price_data/price_2330_20200201.csv

In [24]:
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=20200301&stockNo=2330'
data1 = pd.read_html(requests.get(url).text)[0]
data1.columns = data1.columns.droplevel(0)
data1 = data1.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})

In [39]:
table = pd.read_csv('price_2330_20200201.csv', index_col='Date')
new_table = table.append(data1)
new_table.to_csv('price_2330_20200201.csv', index=False)

/Users/zhongrenguang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

              Volume         成交金額   Open   High    Low  Close    漲跌價差   成交筆數
Date
109/02/03   59711849  18782694826  315.0  316.5  312.0  315.0    -5.0  26483
109/02/04   52208496  16882411296  319.0  326.0  318.0  325.0    10.0  22587
109/02/05   36601453  11985817083  329.0  329.5  324.5  327.5     2.5  16656
109/02/06   29659094   9803038836  329.5  332.5  329.0  332.5     5.0  14246
109/02/07   30055327   9869903253  330.0  330.5  326.0  328.0    -4.5  13075
109/02/10   30814424  10024967927  321.5  328.0  321.0  327.5    -0.5  14825
109/02/11   29062935   9629938182  330.5  332.5  330.0  331.5     4.0  12766
109/02/12   37612639  12593082711  333.5  336.0  333.0  335.0     3.5  17394
109/02/13   23217021   7805299096  338.0  338.0  335.0  335.0     0.0  12563
109/02/14   18326683   6155862838  337.0  337.0  334.5  335.0     0.0   7881
109/02/17   16145079   5354339726  331.5  333.0  330.5  331.5    -3.5   9747
109/02/18   64662604  20957801150  324.5  326.5  322.0  322.0    -9.5  36520
109/02/19   48856218  15881609046  322.5  327.0  322.0  326.5     4.5  16003
109/02/20   27061736   8832642641  328.0  329.0  325.0  325.5    -1.0  11695
109/02/21   22974534   7463007621  325.5  326.5  323.0  325.0    -0.5   9342
109/02/24   42946680  13754512932  319.5  321.5  319.5  320.0    -5.0  18902
109/02/25   38674011  12425785349  320.0  323.5  317.5  322.0     2.0  17366
109/02/26   60768362  19341695595  317.0  320.5  316.5  318.5    -3.5  24310
109/02/27   62401927  19756146876  319.0  320.0  315.0  316.0    -2.5  20633
109/03/02   86372942  26864484400  308.0  317.0  308.0  311.0   -5.00  35320
109/03/03   55169411  17534766696  318.5  320.0  316.0  317.5   +6.50  20713
109/03/04   44745146  14304795666  322.0  322.0  317.0  320.5   +3.00  16118
109/03/05   38223525  12392618100  325.0  326.0  323.0  323.0   +2.50  15107
109/03/06   52807760  16733485610  320.0  320.5  315.0  315.0   -8.00  24175
109/03/09   88633277  27236002054  307.5  310.0  305.5  305.5   -9.50  44882
109/03/10   74869130  22727941511  301.5  309.0  301.0  307.0   +1.50  30268
109/03/11   64923710  19913151529  309.0  310.5  302.0  302.0   -5.00  27176
109/03/12  114173351  33544278206  299.0  299.0  287.0  294.0   -8.00  56989
109/03/13  151268148  42448997546  275.0  294.0  272.5  290.0   -4.00  71990
109/03/16  103933228  29343288916  285.0  291.0  275.5  276.5  -13.50  51292
...              ...          ...    ...    ...    ...    ...     ...    ...
109/03/20  159179726  42110816042  258.5  270.0  256.0  270.0  +22.00  69829
109/03/23   76963709  19851467203  257.0  262.5  252.0  255.0  -15.00  41621
109/03/24   82377933  22207033614  268.0  274.0  266.0  267.5  +12.50  41077
109/03/25   80514199  22368633590  276.5  280.0  274.0  277.0   +9.50  40932
109/03/26   54189633  15108299935  279.5  280.0  275.5  280.0   +3.00  27648
109/03/27   69320306  19324060590  284.0  286.0  273.0  273.0   -7.00  36025
109/03/30   53403956  14205364184  263.5  269.0  262.5  267.5   -5.50  27779
109/03/31   53901923  14712557472  273.0  274.0  269.5  274.0   +6.50  20343
109/03/02   86372942  26864484400  308.0  317.0  308.0  311.0   -5.00  35320
109/03/03   55169411  17534766696  318.5  320.0  316.0  317.5   +6.50  20713
109/03/04   44745146  14304795666  322.0  322.0  317.0  320.5   +3.00  16118
109/03/05   38223525  12392618100  325.0  326.0  323.0  323.0   +2.50  15107
109/03/06   52807760  16733485610  320.0  320.5  315.0  315.0   -8.00  24175
109/03/09   88633277  27236002054  307.5  310.0  305.5  305.5   -9.50  44882
109/03/10   74869130  22727941511  301.5  309.0  301.0  307.0   +1.50  30268
109/03/11   64923710  19913151529  309.0  310.5  302.0  302.0   -5.00  27176
109/03/12  114173351  33544278206  299.0  299.0  287.0  294.0   -8.00  56989
109/03/13  151268148  42448997546  275.0  294.0  272.5  290.0   -4.00  71990
109/03/16  103933228  29343288916  285.0  291.0  275.5  276.5  -13.50  51292
109/03/17  122409651  32936712540  265.0  276.5  265.0  268.0   -8.50  57123
109/03/18  118620643  31555231792  269.5  272.5  260.0  260.0   -8.00  53985
109/03/19  160811697  39559889553  252.0  253.0  235.5  248.0   X0.00  77302
109/03/20  159179726  42110816042  258.5  270.0  256.0  270.0  +22.00  69829
109/03/23   76963709  19851467203  257.0  262.5  252.0  255.0  -15.00  41621
109/03/24   82377933  22207033614  268.0  274.0  266.0  267.5  +12.50  41077
109/03/25   80514199  22368633590  276.5  280.0  274.0  277.0   +9.50  40932
109/03/26   54189633  15108299935  279.5  280.0  275.5  280.0   +3.00  27648
109/03/27   69320306  19324060590  284.0  286.0  273.0  273.0   -7.00  36025
109/03/30   53403956  14205364184  263.5  269.0  262.5  267.5   -5.50  27779
109/03/31   53901923  14712557472  273.0  274.0  269.5  274.0   +6.50  20343

[63 rows x 8 columns]

## 上下在處理重複資料（每天下載完會有很多重複資料）

In [61]:
def crawl_price(stockid, date):
    import requests
    import pandas as pd
    import os
    import time
    import sqlite3
    from talib import abstract
    
    url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=' + str(date) + '&stockNo=' + str(stockid)
    data = pd.read_html(requests.get(url).text)[0]
    data.columns = data.columns.droplevel(0)
    data = data.rename(columns={'日期': 'date', '成交股數': 'volume', '開盤價': 'open', '最高價': 'high', '最低價': 'low', '收盤價': 'close'})
    data['volume'] = data['volume'] / 1000
    path = os.path.join('./price_data', 'price_' + str(stockid) + '.csv') # 路徑要換成下面的
    # 還沒有建立個股的csv時，使用下面的
#     data.to_csv(path, index=True)
    conn = sqlite3.connect('price.db')
    sql_table = pd.read_sql('select * from price_' + str(stockid), conn)
    sql_table = sql_table.append(data)
    sql_table = sql_table.set_index('date')
    sql_table = sql_table[sql_table.index.duplicated() == False]
    ma5 = sql_table['close'].rolling(5).mean()
    ma10 = sql_table['close'].rolling(10).mean()
    ma20 = sql_table['close'].rolling(20).mean()
    volumeMa5 = sql_table['volume'].rolling(5).mean()
    volumeMa10 = sql_table['volume'].rolling(10).mean()
    volumeMa20 = sql_table['volume'].rolling(20).mean()
    kd = abstract.STOCH(sql_table)
    slowj = kd['slowk'] * 3 - kd['slowd'] * 2
    sql_table = sql_table.assign(ma5=ma5, ma10=ma10, ma20=ma20, volumeMa5=volumeMa5, volumeMa10=volumeMa10, volumeMa20=volumeMa20, slowk=kd['slowk'], slowd=kd['slowd'], slowj=slowj)
    sql_table.to_sql('price_' + str(stockid), conn, if_exists='replace')
    
#     table = pd.read_csv(path)
#     new_table = table.append(data)
#     new_table = new_table.set_index('date')
#     new_table = new_table[new_table.index.duplicated() == False]
#     ma5 = new_table['close'].rolling(5).mean()
#     ma10 = new_table['close'].rolling(10).mean()
#     ma20 = new_table['close'].rolling(20).mean()
#     new_table = new_table.assign(ma5=ma5, ma10=ma10, ma20=ma20)
#     new_table.to_csv(path, index=True)
#     time.sleep(2)
    return sql_table
    # 先把每個股票資料都存成個別csv
    # 在進行read_csv，爬下一個月份資料，把資料放進read_csv的table裡面，再存回csv

In [64]:
download_table = [1101, 2317, 2330, 2498]
for d in download_table:
    table = crawl_price(d, '20210901')
table

/Users/zhongrenguang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

,close,high,index,low,ma10,ma20,ma5,open,slowd,slowj,slowk,volume,volumeMa10,volumeMa20,volumeMa5,成交筆數,成交金額,漲跌價差
date,,,,,,,,,,,,,,,,,,
110/04/01,31.20,31.50,0.0,30.80,NaN,NaN,NaN,31.25,NaN,NaN,NaN,17347.848,NaN,NaN,NaN,8659,540310131,0.35
110/04/06,30.95,31.65,1.0,30.90,NaN,NaN,NaN,31.60,NaN,NaN,NaN,8467.673,NaN,NaN,NaN,4349,263719864,-0.25
110/04/07,31.45,32.45,2.0,31.25,NaN,NaN,NaN,31.25,NaN,NaN,NaN,17482.994,NaN,NaN,NaN,8025,555649329,0.50
110/04/08,31.45,31.80,3.0,31.20,NaN,NaN,NaN,31.55,NaN,NaN,NaN,7353.037,NaN,NaN,NaN,3874,231893495,0.00
110/04/09,31.50,31.80,4.0,31.20,NaN,NaN,31.31,31.80,NaN,NaN,NaN,6534.412,NaN,NaN,11437.1928,3196,205640129,0.05
110/04/12,32.80,33.00,5.0,31.50,NaN,NaN,31.63,31.65,NaN,NaN,NaN,17974.759,NaN,NaN,11562.5750,8297,582321315,1.30
110/04/13,33.10,33.90,6.0,32.90,NaN,NaN,32.06,33.00,NaN,NaN,NaN,19428.685,NaN,NaN,13754.7774,8886,648663414,0.30
110/04/14,32.65,33.75,7.0,32.15,NaN,NaN,32.30,33.45,NaN,NaN,NaN,17321.091,NaN,NaN,13722.3968,7546,567666648,-0.45
110/04/15,35.90,35.90,8.0,33.05,NaN,NaN,33.19,33.20,71.321682,81.430709,74.691358,47401.791,NaN,NaN,21732.1476,16539,1679953018,3.25
110/04/16,39.45,39.45,9.0,36.70,33.045,NaN,34.78,37.65,76.925338,99.853028,84.567901,58655.442,21796.7732,NaN,32156.3536,25115,2261411408,3.55
110/04/19,40.10,42.00,10.0,39.55,33.935,NaN,36.24,40.20,84.276493,112.157674,93.570220,54358.138,25497.8022,NaN,39433.0294,26104,2211842509,0.65
110/04/20,39.95,39.95,11.0,38.65,34.835,NaN,37.61,39.70,88.256982,83.384513,86.632826,25438.337,27194.8686,NaN,40634.9598,12974,996242081,-0.15
110/04/21,40.60,41.85,12.0,40.45,35.750,NaN,39.20,41.20,87.207240,69.841540,81.418673,27166.257,28163.1949,NaN,42603.9930,13137,1114623054,0.65
110/04/22,38.00,41.30,13.0,37.25,36.405,NaN,39.62,41.20,76.914240,34.245182,62.691220,31515.475,30579.4387,NaN,39426.7298,14349,1237930564,-2.60
110/04/23,41.80,41.80,14.0,38.65,37.435,NaN,40.09,38.90,70.778333,63.118651,68.225106,39528.001,33878.7976,NaN,35601.2416,17436,1608205908,3.80
110/04/26,44.70,45.70,15.0,42.20,38.625,NaN,41.01,43.50,66.803604,74.876248,69.494485,56775.240,37758.8457,NaN,36084.6620,26557,2514325344,2.90
110/04/27,43.15,43.80,16.0,42.40,39.630,NaN,41.65,43.70,74.104046,105.569548,84.592546,27144.071,38530.3843,NaN,36425.8088,14058,1168599793,-1.55
110/04/28,43.10,45.60,17.0,42.45,40.675,NaN,42.15,42.85,76.608892,74.001150,75.739645,32205.386,40018.8138,NaN,37433.6346,15998,1417435212,-0.05
110/04/29,41.60,44.45,18.0,41.55,41.245,NaN,42.87,43.50,73.543756,33.809715,60.299075,31620.098,38440.6445,NaN,37454.5592,14110,1348635253,-1.50
110/05/03,42.15,44.15,NaN,41.05,41.515,37.2800,42.94,42.00,60.316313,14.098029,44.910218,29513.738,35526.4741,28661.62365,35451.7066,14444,1261823125,0.55
110/05/04,40.60,43.85,NaN,38.65,41.565,37.7500,42.12,43.35,45.465036,2.627368,31.185813,37176.796,33808.3399,29653.07105,31532.0178,17086,1521931835,-1.55
110/05/05,39.45,41.85,NaN,39.20,41.515,38.1750,41.38,41.10,32.390262,-1.556264,21.074753,19610.968,33225.6030,30210.23580,30025.3972,9771,792069360,-1.15
110/05/06,39.65,40.85,NaN,39.10,41.420,38.5850,40.69,40.20,23.732380,9.344964,18.936575,14490.201,31957.9974,30060.59615,26482.3602,6669,578721641,0.20
110/05/07,40.50,41.50,NaN,39.75,41.670,39.0375,40.47,40.60,20.269169,21.850197,20.796178,13708.918,30177.3417,30378.39020,22900.1242,6569,557082288,0.85
110/05/10,40.55,41.35,NaN,40.40,41.545,39.4900,40.15,41.10,22.957163,41.501879,29.138735,8944.890,27119.0306,30498.91410,18786.3546,4422,364582032,0.05
110/05/11,38.00,39.85,NaN,37.10,40.875,39.7500,39.63,39.85,26.547437,36.027320,29.707398,23429.948,23784.5014,30771.67355,16036.9850,10770,899685917,-2.55
110/05/12,36.25,39.45,NaN,34.90,40.185,39.9075,38.99,38.50,28.053197,19.833981,25.313458,31618.650,24231.9593,31381.17180,18438.5214,12913,1173477146,-1.75
110/05/13,35.05,37.35,NaN,35.05,39.380,40.0275,38.07,36.00,22.970801,-4.266961,13.891547,20951.051,23106.5258,31562.66980,19730.6914,9358,749798405,-1.20
110/05/14,34.50,36.70,NaN,34.25,38.670,39.9575,36.87,36.10,15.984824,-5.721249,8.749466,17756.567,21720.1727,30080.40860,20540.2212,7512,624705264,-0.55
110/05/17,32.10,34.20,NaN,31.55,37.665,39.5900,35.18,32.25,8.927045,-5.433729,4.140120,17990.624,20567.8613,28047.16770,22349.3680,7826,588596218,-2.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110/08/03,41.45,41.50,NaN,39.85,37.910,37.7400,38.78,39.90,84.107330,119.150655,95.788438,20068.965,9713.0662,8234.54615,13833.0824,9677,819686694,1.50
110/08/04,41.55,42.10,NaN,40.90,38.420,37.9100,40.02,41.50,93.888370,94.020458,93.932399,13958.962,10547.1504,8442.15880,15055.5812,6601,579516825,0.10
110/08/05,41.90,42.00,NaN,41.00,38.930,38.1075,40.82,41.55,94.991831,95.780306,95.254656,11327.777,11192.2829,8544.20040,15302.9888,6044,471697770,0.35
110/08/06,40.35,42.30,NaN,40.30,39.245,38.2350,41.04,41.80,87.796211,47.012313,74.201579,11504.106,11725.1715,8799.69865,14016.9656,5583,472491132,-1.55
110/08/09,38.60,39.80,NaN,38.50,39.305,38.2750,40.77,39.00,71.402379,-8.552050,44.750903,11458.664,12305.5619,9101.59885,13663.6948,5760,446584399,-1.75
110/08/10,38.90,39.60,NaN,38.65,39.520,38.3500,40.26,39.15,45.120101,-41.016734,16.407823,5875.318,12329.0239,8903.39060,10824.9654,2713,229644680,0.30
110/08/11,37.80,38.95,NaN,37.40,39.765,38.4100,39.51,38.85,22.755260,-24.189359,7.107053,7297.493,12274.1264,8941.46930,9492.6716,3585,278154579,-1.10
110/08/12,37.70,38.50,NaN,37.65,39.745,38.3925,38.67,38.10,10.595184,3.621661,8.270677,3649.548,11630.0073,8789.67855,7957.0258,1864,138811811,-0.10
110/08/13,37.00,38.05,NaN,36.75,39.520,38.3625,38.00,38.00,7.623958,7.234519,7.494145,5510.177,10387.6028,8826.77875,6758.2400,2726,205615558,-0.70
110/08/16,36.40,37.55,NaN,36.00,39.165,38.3075,37.56,36.70,8.080527,9.269226,8.476760,5759.907,9641.0917,8909.85560,5618.4886,2957,210946325,-0.60
110/08/17,35.35,36.95,NaN,35.30,38.555,38.2325,36.85,36.70,7.621157,5.435382,6.892565,5983.447,8232.5399,8972.80305,5640.1144,3342,215174727,-1.05
110/08/18,36.10,36.10,NaN,34.80,38.010,38.2150,36.51,35.35,10.413787,26.788535,15.872036,6200.958,7456.7395,9001.94495,5420.8074,3278,220693400,0.75
110/08/19,34.65,35.85,NaN,34.50,37.285,38.1075,35.90,35.70,12.113795,16.502760,13.576783,6535.352,6977.4970,9084.88995,5997.9682,3454,229438913,-1.45
110/08/20,34.65,35.55,NaN,34.25,36.715,37.9800,35.43,34.95,15.536462,20.408775,17.160566,4164.011,6243.4875,8984.32950,5728.7350,2368,145199352,0.00
110/08/23,35.50,35.65,NaN,34.85,36.405,37.8550,35.25,35.05,17.206101,28.230658,20.880954,2736.222,5371.2433,8838.40260,5123.9980,1491,96768056,0.85
110/08/24,35.25,36.15,NaN,35.20,36.040,37.7800,35.23,36.15,25.019294,61.010499,37.016362,3566.226,5140.3341,8734.67900,4640.5538,1698,127098475,-0.25
110/08/25,35.75,35.95,NaN,35.15,35.835,37.8000,35.16,35.45,39.063021,99.749201,59.291748,2815.408,4692.1256,8483.12600,3963.4438,1365,100338664,0.50
110/08/26,35.15,36.35,NaN,35.10,35.580,37.6625,35.26,36.00,51.484491,71.467108,58.145363,4136.018,4740.7726,8185.38995,3483.5770,2072,147004921,-0.60
110/08/27,35.15,35.45,NaN,35.00,35.395,37.4575,35.36,35.35,54.901761,32.000990,47.268170,2312.058,4420.9607,7404.28175,3113.1864,1327,81482328,0.00
110/08/30,35.85,35.85,NaN,35.40,35.340,37.2525,35.43,35.50,49.117856,27.584393,41.940035,2583.952,4103.3652,6872.22845,3082.7324,1770,92174280,0.70
110/08/31,35.55,35.95,NaN,35.40,35.360,36.9575,35.49,35.95,43.480925,36.741855,41.234568,2014.998,3706.5203,5969.53010,2772.4868,1211,71747532,-0.30
110/09/01,36.05,36.20,NaN,35.65,35.355,36.6825,35.55,35.70,47.889477,85.702528,60.493827,1988.996,3285.3241,5371.03180,2607.2044,1226,71556166,0.50
110/09/02,35.55,36.50,NaN,35.40,35.445,36.3650,35.63,36.20,51.152263,52.880658,51.728395,3429.837,2974.7726,4976.13480,2465.9682,1834,123201434,-0.50
110/09/03,36.00,36.10,NaN,35.55,35.580,36.1475,35.80,35.90,56.184063,56.621773,56.329966,2013.986,2759.7701,4501.62880,2406.3538,1232,72243982,0.45
110/09/06,35.30,36.20,NaN,35.25,35.560,35.9825,35.69,36.10,46.598578,2.014964,31.737374,2516.515,2737.7994,4054.52135,2392.8664,1457,89431113,-0.70
110/09/07,34.70,35.55,NaN,34.60,35.505,35.7725,35.52,35.25,36.445626,-9.082639,21.269537,3949.377,2776.1145,3958.22430,2779.7422,2229,137887024,-0.60
110/09/08,34.40,35.30,NaN,34.30,35.370,35.6025,35.19,34.95,19.203261,-24.597909,4.602871,3157.399,2810.3136,3751.21960,3013.4228,1926,109790065,-0.30
110/09/09,34.60,34.95,NaN,34.55,35.315,35.4475,35.00,34.60,11.468368,2.661350,8.532695,1520.300,2548.7418,3644.75720,2631.5154,1022,52820845,0.20
110/09/10,34.85,35.10,NaN,34.70,35.285,35.3400,34.77,34.80,9.854333,29.573631,16.427432,1522.683,2469.8043,3445.38250,2533.2548,944,53079041,0.25
110/09/13,37.85,37.85,NaN,34.85,35.485,35.4125,35.28,35.00,24.401914,95.933014,48.245614,14636.395,3675.0486,3889.20690,4957.2308,7126,537938798,3.00

## twstock

In [118]:
import twstock
from twstock import codes
import sqlite3
import pandas as pd
import json
from ast import literal_eval

In [197]:
# twstock.realtime.mock = False
# arr = ['1101', '2330', '2317', '2498']
# data = twstock.realtime.get(arr)      
# data

# 一次抓取所有台股資料
arr_all = []
conn_all_stock = sqlite3.connect('stockInfo.db')
all_stock_table = pd.read_sql('select 有價證券代號及名稱 from stock_name', conn_all_stock)
all_stock_table = all_stock_table.iloc[:953]
all_stock_table

        有價證券代號及名稱
0              股票
1         1101　台泥
2         1102　亞泥
3         1103　嘉泥
4         1104　環泥
5         1108　幸福
6         1109　信大
7         1110　東泥
8         1201　味全
9         1203　味王
10        1210　大成
11        1213　大飲
12        1215　卜蜂
13        1216　統一
14       1217　愛之味
15        1218　泰山
16        1219　福壽
17        1220　台榮
18       1225　福懋油
19        1227　佳格
20        1229　聯華
21       1231　聯華食
22       1232　大統益
23        1233　天仁
24        1234　黑松
25        1235　興泰
26        1236　宏亞
27   1256　鮮活果汁-KY
28        1301　台塑
29        1303　南亞
..            ...
923       9911　櫻花
924       9912　偉聯
925      9914　美利達
926      9917　中保科
927      9918　欣天然
928      9919　康那香
929       9921　巨大
930       9924　福興
931       9925　新保
932       9926　新海
933       9927　泰銘
934       9928　中視
935       9929　秋雨
936     9930　中聯資源
937       9931　欣高
938       9933　中鼎
939       9934　成霖
940      9935　慶豐富
941       9937　全國
942       9938　百和
943       9939　宏全
944       9940　信義
945       9941　裕融
946       9942　茂順
947      9943　好樂迪
948       9944　新麗
949      9945　潤泰新
950     9946　三發地產
951       9955　佳龍
952      9958　世紀鋼

[953 rows x 1 columns]

In [198]:
arr_list = all_stock_table['有價證券代號及名稱'].tolist()
del(arr_list[0])
del(arr_list[651])

In [199]:
for i in arr_list:
    stockid = i.split('\u3000')[0]
    arr_all.append(stockid)

In [200]:
arr_all

['1101',
 '1102',
 '1103',
 '1104',
 '1108',
 '1109',
 '1110',
 '1201',
 '1203',
 '1210',
 '1213',
 '1215',
 '1216',
 '1217',
 '1218',
 '1219',
 '1220',
 '1225',
 '1227',
 '1229',
 '1231',
 '1232',
 '1233',
 '1234',
 '1235',
 '1236',
 '1256',
 '1301',
 '1303',
 '1304',
 '1305',
 '1307',
 '1308',
 '1309',
 '1310',
 '1312',
 '1313',
 '1314',
 '1315',
 '1316',
 '1319',
 '1321',
 '1323',
 '1324',
 '1325',
 '1326',
 '1337',
 '1338',
 '1339',
 '1340',
 '1341',
 '1342',
 '1402',
 '1409',
 '1410',
 '1413',
 '1414',
 '1416',
 '1417',
 '1418',
 '1419',
 '1423',
 '1432',
 '1434',
 '1435',
 '1436',
 '1437',
 '1438',
 '1439',
 '1440',
 '1441',
 '1442',
 '1443',
 '1444',
 '1445',
 '1446',
 '1447',
 '1449',
 '1451',
 '1452',
 '1453',
 '1454',
 '1455',
 '1456',
 '1457',
 '1459',
 '1460',
 '1463',
 '1464',
 '1465',
 '1466',
 '1467',
 '1468',
 '1470',
 '1471',
 '1472',
 '1473',
 '1474',
 '1475',
 '1476',
 '1477',
 '1503',
 '1504',
 '1506',
 '1507',
 '1512',
 '1513',
 '1514',
 '1515',
 '1516',
 '1517',
 '1519',
 '1521',
 '1522',
 '1524',
 '1525',
 '1526',
 '1527',
 '1528',
 '1529',
 '1530',
 '1531',
 '1532',
 '1533',
 '1535',
 '1536',
 '1537',
 '1538',
 '1539',
 '1540',
 '1541',
 '1558',
 '1560',
 '1568',
 '1582',
 '1583',
 '1587',
 '1589',
 '1590',
 '1592',
 '1597',
 '1598',
 '1603',
 '1604',
 '1605',
 '1608',
 '1609',
 '1611',
 '1612',
 '1614',
 '1615',
 '1616',
 '1617',
 '1618',
 '1626',
 '1701',
 '1702',
 '1707',
 '1708',
 '1709',
 '1710',
 '1711',
 '1712',
 '1713',
 '1714',
 '1717',
 '1718',
 '1720',
 '1721',
 '1722',
 '1723',
 '1724',
 '1725',
 '1726',
 '1727',
 '1730',
 '1731',
 '1732',
 '1733',
 '1734',
 '1735',
 '1736',
 '1737',
 '1760',
 '1762',
 '1773',
 '1776',
 '1783',
 '1786',
 '1789',
 '1795',
 '1802',
 '1805',
 '1806',
 '1808',
 '1809',
 '1810',
 '1817',
 '1903',
 '1904',
 '1905',
 '1906',
 '1907',
 '1909',
 '2002',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2012',
 '2013',
 '2014',
 '2015',
 '2017',
 '2020',
 '2022',
 '2023',
 '2024',
 '2025',
 '2027',
 '2028',
 '2029',
 '2030',
 '2031',
 '2032',
 '2033',
 '2034',
 '2038',
 '2049',
 '2059',
 '2062',
 '2069',
 '2101',
 '2102',
 '2103',
 '2104',
 '2105',
 '2106',
 '2107',
 '2108',
 '2109',
 '2114',
 '2115',
 '2201',
 '2204',
 '2206',
 '2207',
 '2208',
 '2211',
 '2227',
 '2228',
 '2231',
 '2233',
 '2236',
 '2239',
 '2241',
 '2243',
 '2247',
 '2301',
 '2302',
 '2303',
 '2305',
 '2308',
 '2312',
 '2313',
 '2314',
 '2316',
 '2317',
 '2321',
 '2323',
 '2324',
 '2327',
 '2328',
 '2329',
 '2330',
 '2331',
 '2332',
 '2337',
 '2338',
 '2340',
 '2342',
 '2344',
 '2345',
 '2347',
 '2348',
 '2349',
 '2351',
 '2352',
 '2353',
 '2354',
 '2355',
 '2356',
 '2357',
 '2358',
 '2359',
 '2360',
 '2362',
 '2363',
 '2364',
 '2365',
 '2367',
 '2368',
 '2369',
 '2371',
 '2373',
 '2374',
 '2375',
 '2376',
 '2377',
 '2379',
 '2380',
 '2382',
 '2383',
 '2385',
 '2387',
 '2388',
 '2390',
 '2392',
 '2393',
 '2395',
 '2397',
 '2399',
 '2401',
 '2402',
 '2404',
 '2405',
 '2406',
 '2408',
 '2409',
 '2412',
 '2413',
 '2414',
 '2415',
 '2417',
 '2419',
 '2420',
 '2421',
 '2423',
 '2424',
 '2425',
 '2426',
 '2427',
 '2428',
 '2429',
 '2430',
 '2431',
 '2433',
 '2434',
 '2436',
 '2438',
 '2439',
 '2440',
 '2441',
 '2442',
 '2443',
 '2444',
 '2449',
 '2450',
 '2451',
 '2453',
 '2454',
 '2455',
 '2456',
 '2457',
 '2458',
 '2459',
 '2460',
 '2461',
 '2462',
 '2464',
 '2465',
 '2466',
 '2467',
 '2468',
 '2471',
 '2472',
 '2474',
 '2476',
 '2477',
 '2478',
 '2480',
 '2481',
 '2482',
 '2483',
 '2484',
 '2485',
 '2486',
 '2488',
 '2489',
 '2491',
 '2492',
 '2493',
 '2495',
 '2496',
 '2497',
 '2498',
 '2501',
 '2504',
 '2505',
 '2506',
 '2509',
 '2511',
 '2514',
 '2515',
 '2516',
 '2520',
 '2524',
 '2527',
 '2528',
 '2530',
 '2534',
 '2535',
 '2536',
 '2537',
 '2538',
 '2539',
 '2540',
 '2542',
 '2543',
 '2545',
 '2546',
 '2547',
 '2548',
 '2597',
 '2601',
 '2603',
 '2605',
 '2606',
 '2607',
 '2608',
 '2609',
 '2610',
 '2611',
 '2612',
 '2613',
 '2614',
 '2615',
 '2616',
 '2617',
 '2618',
 '2630',
 '2633',
 '2634',
 '2636',
 '2637',
 '2642',
 '2701',
 '2702',
 '2704',
 '2705',
 '2706',
 '2707',
 '2712',
 '2722',
 '2723',
 '2727',
 '2731',
 '2739',
 '2748',
 '2801',
 '2809',
 '2812',
 '2816',
 '2820',
 '2823',
 '2832',
 '2834',
 '2836',
 '2838',
 '2841',
 '2845',
 '2849',
 '2850',
 '2851',
 '2852',
 '2855',
 '2867',
 '2880',
 '2881',
 '2882',
 '2883',
 '2884',
 '2885',
 '2886',
 '2887',
 '2888',
 '2889',
 '2890',
 '2891',
 '2892',
 '2897',
 '2901',
 '2903',
 '2904',
 '2905',
 '2906',
 '2908',
 '2910',
 '2911',
 '2912',
 '2913',
 '2915',
 '2923',
 '2929',
 '2936',
 '2939',
 '3002',
 '3003',
 '3004',
 '3005',
 '3006',
 '3008',
 '3010',
 '3011',
 '3013',
 '3014',
 '3015',
 '3016',
 '3017',
 '3018',
 '3019',
 '3021',
 '3022',
 '3023',
 '3024',
 '3025',
 '3026',
 '3027',
 '3028',
 '3029',
 '3030',
 '3031',
 '3032',
 '3033',
 '3034',
 '3035',
 '3036',
 '3037',
 '3038',
 '3040',
 '3041',
 '3042',
 '3043',
 '3044',
 '3045',
 '3046',
 '3047',
 '3048',
 '3049',
 '3050',
 '3051',
 '3052',
 '3054',
 '3055',
 '3056',
 '3057',
 '3058',
 '3059',
 '3060',
 '3062',
 '3090',
 '3092',
 '3094',
 '3130',
 '3138',
 '3149',
 '3164',
 '3167',
 '3189',
 '3209',
 '3229',
 '3231',
 '3257',
 '3266',
 '3296',
 '3305',
 '3308',
 '3311',
 '3312',
 '3321',
 '3338',
 '3346',
 '3356',
 '3376',
 '3380',
 '3383',
 '3406',
 '3413',
 '3416',
 '3419',
 '3432',
 '3437',
 '3443',
 '3450',
 '3454',
 '3481',
 '3494',
 '3501',
 '3504',
 '3515',
 '3518',
 '3528',
 '3530',
 '3532',
 '3533',
 '3535',
 '3536',
 '3543',
 '3545',
 '3550',
 '3557',
 '3563',
 '3576',
 '3583',
 '3588',
 '3591',
 '3593',
 '3596',
 '3605',
 '3607',
 '3617',
 '3622',
 '3645',
 '3653',
 '3661',
 '3665',
 '3669',
 '3673',
 '3679',
 '3682',
 '3686',
 '3694',
 '3701',
 '3702',
 '3703',
 '3704',
 '3705',
 '3706',
 '3708',
 '3711',
 '3712',
 '3714',
 '4104',
 '4106',
 '4108',
 '4119',
 '4133',
 '4137',
 '4141',
 '4142',
 '4155',
 '4164',
 '4190',
 '4306',
 '4414',
 '4426',
 '4438',
 '4439',
 '4526',
 '4532',
 '4536',
 '4540',
 '4545',
 '4551',
 '4552',
 '4555',
 '4557',
 '4560',
 '4562',
 '4564',
 '4566',
 '4571',
 '4572',
 '4576',
 '4581',
 '4720',
 '4722',
 '4737',
 '4739',
 '4746',
 '4755',
 '4763',
 '4764',
 '4766',
 '4807',
 '4904',
 '4906',
 '4912',
 '4915',
 '4916',
 '4919',
 '4927',
 '4930',
 '4934',
 '4935',
 '4938',
 '4942',
 '4943',
 '4952',
 '4956',
 '4958',
 '4960',
 '4961',
 '4967',
 '4968',
 '4976',
 '4977',
 '4989',
 '4994',
 '4999',
 '5007',
 '5203',
 '5215',
 '5225',
 '5234',
 '5243',
 '5258',
 '5269',
 '5283',
 '5284',
 '5285',
 '5288',
 '5388',
 '5434',
 '5469',
 '5471',
 '5484',
 '5515',
 '5519',
 '5521',
 '5522',
 '5525',
 '5531',
 '5533',
 '5534',
 '5538',
 '5546',
 '5607',
 '5608',
 '5706',
 '5871',
 '5876',
 '5880',
 '5906',
 '5907',
 '6005',
 '6024',
 '6108',
 '6112',
 '6115',
 '6116',
 '6117',
 '6120',
 '6128',
 '6131',
 '6133',
 '6136',
 '6139',
 '6141',
 '6142',
 '6152',
 '6153',
 '6155',
 '6164',
 '6165',
 '6166',
 '6168',
 '6172',
 '6176',
 '6177',
 '6183',
 '6184',
 '6189',
 '6191',
 '6192',
 '6196',
 '6197',
 '6201',
 '6202',
 '6205',
 '6206',
 '6209',
 '6213',
 '6214',
 '6215',
 '6216',
 '6224',
 '6225',
 '6226',
 '6230',
 '6235',
 '6239',
 '6243',
 '6251',
 '6257',
 '6269',
 '6271',
 '6277',
 '6278',
 '6281',
 '6282',
 '6283',
 '6285',
 '6288',
 '6289',
 '6405',
 '6409',
 '6412',
 '6414',
 '6415',
 '6416',
 '6426',
 '6431',
 '6438',
 '6442',
 '6443',
 '6449',
 '6451',
 '6456',
 '6464',
 '6477',
 '6491',
 '6504',
 '6505',
 '6515',
 '6525',
 '6531',
 '6533',
 '6541',
 '6552',
 '6558',
 '6573',
 '6579',
 '6581',
 '6582',
 '6591',
 '6592',
 '6598',
 '6605',
 '6625',
 '6641',
 '6655',
 '6666',
 '6668',
 '6669',
 '6670',
 '6671',
 '6672',
 '6674',
 '6698',
 '6706',
 '6715',
 '6743',
 '6754',
 '6756',
 '6768',
 '6776',
 '6781',
 '8011',
 '8016',
 '8021',
 '8028',
 '8033',
 '8039',
 '8046',
 '8070',
 '8072',
 '8081',
 '8101',
 '8103',
 '8104',
 '8105',
 '8110',
 '8112',
 '8114',
 '8131',
 '8150',
 '8163',
 '8201',
 '8210',
 '8213',
 '8215',
 '8222',
 '8249',
 '8261',
 '8271',
 '8341',
 '8367',
 '8374',
 '8404',
 '8411',
 '8422',
 '8427',
 '8429',
 '8442',
 '8443',
 '8454',
 '8462',
 '8463',
 '8464',
 '8466',
 '8467',
 '8473',
 '8478',
 '8480',
 '8481',
 '8482',
 '8488',
 '8499',
 '8926',
 '8940',
 '8996',
 '9802',
 '9902',
 '9904',
 '9905',
 '9906',
 '9907',
 '9908',
 '9910',
 '9911',
 '9912',
 '9914',
 '9917',
 '9918',
 '9919',
 '9921',
 '9924',
 '9925',
 '9926',
 '9927',
 '9928',
 '9929',
 '9930',
 '9931',
 '9933',
 '9934',
 '9935',
 '9937',
 '9938',
 '9939',
 '9940',
 '9941',
 '9942',
 '9943',
 '9944',
 '9945',
 '9946',
 '9955',
 '9958']

In [207]:
len(arr_all)

951

In [205]:
data = twstock.realtime.get(arr_all[:300])      
data

ConnectionError: HTTPConnectionPool(host='mis.twse.com.tw', port=80): Max retries exceeded with url: /stock/index.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2c6faa510>: Failed to establish a new connection: [Errno 51] Network is unreachable'))

In [121]:
table = data['1101']['realtime']
table

{'latest_trade_price': '51.4000',
 'trade_volume': '2036',
 'accumulate_trade_volume': '52168',
 'best_bid_price': ['51.4000', '51.3000', '51.2000', '51.1000', '51.0000'],
 'best_bid_volume': ['244', '336', '353', '575', '769'],
 'best_ask_price': ['51.5000', '51.6000', '51.7000', '51.8000', '51.9000'],
 'best_ask_volume': ['1539', '640', '874', '1348', '1119'],
 'open': '51.1000',
 'high': '52.0000',
 'low': '50.7000'}

In [122]:
conn = sqlite3.connect('twstock.db')
df = pd.DataFrame(list(table.items())).T
df.columns = df.iloc[0]
df = df.drop(0)
df
# table.keys()

,latest_trade_price,trade_volume,accumulate_trade_volume,best_bid_price,best_bid_volume,best_ask_price,best_ask_volume,open,high,low
1,51.4000,2036,52168,"[51.4000, 51.3000, 51.2000, 51.1000, 51.0000]","[244, 336, 353, 575, 769]","[51.5000, 51.6000, 51.7000, 51.8000, 51.9000]","[1539, 640, 874, 1348, 1119]",51.1000,52.0000,50.7000