In [46]:
import requests
import pandas as pd
import os

In [52]:
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=20200201&stockNo=2330'
data = pd.read_html(requests.get(url).text)[0]
data.columns = data.columns.droplevel(0)
# data.columns = data.columns(['Date', 'Volume', '成交金額', 'Open', 'High', 'Low', 'Close', '漲跌價差','成交筆數'])
data = data.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})
path = os.path.join('./price_data', 'price_2330_20200201.csv')
print(path)
data.to_csv(path, index=False)

./price_data/price_2330_20200201.csv

In [24]:
url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=20200301&stockNo=2330'
data1 = pd.read_html(requests.get(url).text)[0]
data1.columns = data1.columns.droplevel(0)
data1 = data1.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})

In [39]:
table = pd.read_csv('price_2330_20200201.csv', index_col='Date')
new_table = table.append(data1)
new_table.to_csv('price_2330_20200201.csv', index=False)

/Users/zhongrenguang/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

              Volume         成交金額   Open   High    Low  Close    漲跌價差   成交筆數
Date
109/02/03   59711849  18782694826  315.0  316.5  312.0  315.0    -5.0  26483
109/02/04   52208496  16882411296  319.0  326.0  318.0  325.0    10.0  22587
109/02/05   36601453  11985817083  329.0  329.5  324.5  327.5     2.5  16656
109/02/06   29659094   9803038836  329.5  332.5  329.0  332.5     5.0  14246
109/02/07   30055327   9869903253  330.0  330.5  326.0  328.0    -4.5  13075
109/02/10   30814424  10024967927  321.5  328.0  321.0  327.5    -0.5  14825
109/02/11   29062935   9629938182  330.5  332.5  330.0  331.5     4.0  12766
109/02/12   37612639  12593082711  333.5  336.0  333.0  335.0     3.5  17394
109/02/13   23217021   7805299096  338.0  338.0  335.0  335.0     0.0  12563
109/02/14   18326683   6155862838  337.0  337.0  334.5  335.0     0.0   7881
109/02/17   16145079   5354339726  331.5  333.0  330.5  331.5    -3.5   9747
109/02/18   64662604  20957801150  324.5  326.5  322.0  322.0    -9.5  36520
109/02/19   48856218  15881609046  322.5  327.0  322.0  326.5     4.5  16003
109/02/20   27061736   8832642641  328.0  329.0  325.0  325.5    -1.0  11695
109/02/21   22974534   7463007621  325.5  326.5  323.0  325.0    -0.5   9342
109/02/24   42946680  13754512932  319.5  321.5  319.5  320.0    -5.0  18902
109/02/25   38674011  12425785349  320.0  323.5  317.5  322.0     2.0  17366
109/02/26   60768362  19341695595  317.0  320.5  316.5  318.5    -3.5  24310
109/02/27   62401927  19756146876  319.0  320.0  315.0  316.0    -2.5  20633
109/03/02   86372942  26864484400  308.0  317.0  308.0  311.0   -5.00  35320
109/03/03   55169411  17534766696  318.5  320.0  316.0  317.5   +6.50  20713
109/03/04   44745146  14304795666  322.0  322.0  317.0  320.5   +3.00  16118
109/03/05   38223525  12392618100  325.0  326.0  323.0  323.0   +2.50  15107
109/03/06   52807760  16733485610  320.0  320.5  315.0  315.0   -8.00  24175
109/03/09   88633277  27236002054  307.5  310.0  305.5  305.5   -9.50  44882
109/03/10   74869130  22727941511  301.5  309.0  301.0  307.0   +1.50  30268
109/03/11   64923710  19913151529  309.0  310.5  302.0  302.0   -5.00  27176
109/03/12  114173351  33544278206  299.0  299.0  287.0  294.0   -8.00  56989
109/03/13  151268148  42448997546  275.0  294.0  272.5  290.0   -4.00  71990
109/03/16  103933228  29343288916  285.0  291.0  275.5  276.5  -13.50  51292
...              ...          ...    ...    ...    ...    ...     ...    ...
109/03/20  159179726  42110816042  258.5  270.0  256.0  270.0  +22.00  69829
109/03/23   76963709  19851467203  257.0  262.5  252.0  255.0  -15.00  41621
109/03/24   82377933  22207033614  268.0  274.0  266.0  267.5  +12.50  41077
109/03/25   80514199  22368633590  276.5  280.0  274.0  277.0   +9.50  40932
109/03/26   54189633  15108299935  279.5  280.0  275.5  280.0   +3.00  27648
109/03/27   69320306  19324060590  284.0  286.0  273.0  273.0   -7.00  36025
109/03/30   53403956  14205364184  263.5  269.0  262.5  267.5   -5.50  27779
109/03/31   53901923  14712557472  273.0  274.0  269.5  274.0   +6.50  20343
109/03/02   86372942  26864484400  308.0  317.0  308.0  311.0   -5.00  35320
109/03/03   55169411  17534766696  318.5  320.0  316.0  317.5   +6.50  20713
109/03/04   44745146  14304795666  322.0  322.0  317.0  320.5   +3.00  16118
109/03/05   38223525  12392618100  325.0  326.0  323.0  323.0   +2.50  15107
109/03/06   52807760  16733485610  320.0  320.5  315.0  315.0   -8.00  24175
109/03/09   88633277  27236002054  307.5  310.0  305.5  305.5   -9.50  44882
109/03/10   74869130  22727941511  301.5  309.0  301.0  307.0   +1.50  30268
109/03/11   64923710  19913151529  309.0  310.5  302.0  302.0   -5.00  27176
109/03/12  114173351  33544278206  299.0  299.0  287.0  294.0   -8.00  56989
109/03/13  151268148  42448997546  275.0  294.0  272.5  290.0   -4.00  71990
109/03/16  103933228  29343288916  285.0  291.0  275.5  276.5  -13.50  51292
109/03/17  122409651  32936712540  265.0  276.5  265.0  268.0   -8.50  57123
109/03/18  118620643  31555231792  269.5  272.5  260.0  260.0   -8.00  53985
109/03/19  160811697  39559889553  252.0  253.0  235.5  248.0   X0.00  77302
109/03/20  159179726  42110816042  258.5  270.0  256.0  270.0  +22.00  69829
109/03/23   76963709  19851467203  257.0  262.5  252.0  255.0  -15.00  41621
109/03/24   82377933  22207033614  268.0  274.0  266.0  267.5  +12.50  41077
109/03/25   80514199  22368633590  276.5  280.0  274.0  277.0   +9.50  40932
109/03/26   54189633  15108299935  279.5  280.0  275.5  280.0   +3.00  27648
109/03/27   69320306  19324060590  284.0  286.0  273.0  273.0   -7.00  36025
109/03/30   53403956  14205364184  263.5  269.0  262.5  267.5   -5.50  27779
109/03/31   53901923  14712557472  273.0  274.0  269.5  274.0   +6.50  20343

[63 rows x 8 columns]

## 上下在處理重複資料（每天下載完會有很多重複資料）

In [41]:
new_table=new_table.set_index('Date')
new_table = new_table[new_table.index.duplicated() == False]
new_table

           Close   High    Low   Open     Volume   成交筆數         成交金額    漲跌價差
Date
NaN        315.0  316.5  312.0  315.0   59711849  26483  18782694826    -5.0
109/03/02  311.0  317.0  308.0  308.0   86372942  35320  26864484400   -5.00
109/03/03  317.5  320.0  316.0  318.5   55169411  20713  17534766696   +6.50
109/03/04  320.5  322.0  317.0  322.0   44745146  16118  14304795666   +3.00
109/03/05  323.0  326.0  323.0  325.0   38223525  15107  12392618100   +2.50
109/03/06  315.0  320.5  315.0  320.0   52807760  24175  16733485610   -8.00
109/03/09  305.5  310.0  305.5  307.5   88633277  44882  27236002054   -9.50
109/03/10  307.0  309.0  301.0  301.5   74869130  30268  22727941511   +1.50
109/03/11  302.0  310.5  302.0  309.0   64923710  27176  19913151529   -5.00
109/03/12  294.0  299.0  287.0  299.0  114173351  56989  33544278206   -8.00
109/03/13  290.0  294.0  272.5  275.0  151268148  71990  42448997546   -4.00
109/03/16  276.5  291.0  275.5  285.0  103933228  51292  29343288916  -13.50
109/03/17  268.0  276.5  265.0  265.0  122409651  57123  32936712540   -8.50
109/03/18  260.0  272.5  260.0  269.5  118620643  53985  31555231792   -8.00
109/03/19  248.0  253.0  235.5  252.0  160811697  77302  39559889553   X0.00
109/03/20  270.0  270.0  256.0  258.5  159179726  69829  42110816042  +22.00
109/03/23  255.0  262.5  252.0  257.0   76963709  41621  19851467203  -15.00
109/03/24  267.5  274.0  266.0  268.0   82377933  41077  22207033614  +12.50
109/03/25  277.0  280.0  274.0  276.5   80514199  40932  22368633590   +9.50
109/03/26  280.0  280.0  275.5  279.5   54189633  27648  15108299935   +3.00
109/03/27  273.0  286.0  273.0  284.0   69320306  36025  19324060590   -7.00
109/03/30  267.5  269.0  262.5  263.5   53403956  27779  14205364184   -5.50
109/03/31  274.0  274.0  269.5  273.0   53901923  20343  14712557472   +6.50

In [56]:
def crawl_price(stockid, date):
    import requests
    import pandas as pd
    import os
    import time
    import sqlite3
    
    url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=' + str(date) + '&stockNo=' + str(stockid)
    data = pd.read_html(requests.get(url).text)[0]
    data.columns = data.columns.droplevel(0)
    data = data.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})
    path = os.path.join('./price_data', 'price_' + str(stockid) + '.csv') # 路徑要換成下面的
    # 還沒有建立個股的csv時，使用下面的
#     data.to_csv(path, index=True)
    conn = sqlite3.connect('price.db')
    sql_table = pd.read_sql('select * from price_' + str(stockid), conn)
    sql_table = sql_table.append(data)
    sql_table = sql_table.set_index('Date')
    sql_table = sql_table[sql_table.index.duplicated() == False]
    sql_table.to_sql('price_' + str(stockid), conn, if_exists='replace')
    
    table = pd.read_csv(path)
    new_table = table.append(data)
    new_table = new_table.set_index('Date')
    new_table = new_table[new_table.index.duplicated() == False]
    new_table.to_csv(path, index=True)
    time.sleep(2)
    return sql_table
    # 先把每個股票資料都存成個別csv
    # 在進行read_csv，爬下一個月份資料，把資料放進read_csv的table裡面，再存回csv

In [62]:
download_table = [1101, 2317, 2330, 2498]
for d in download_table:
    table = crawl_price(d, '20210801')
table

,Close,High,Low,Open,Volume,index,成交筆數,成交金額,漲跌價差
Date,,,,,,,,,
110/04/01,31.20,31.50,30.80,31.25,17347848,0.0,8659,540310131,0.35
110/04/06,30.95,31.65,30.90,31.60,8467673,1.0,4349,263719864,-0.25
110/04/07,31.45,32.45,31.25,31.25,17482994,2.0,8025,555649329,0.50
110/04/08,31.45,31.80,31.20,31.55,7353037,3.0,3874,231893495,0.00
110/04/09,31.50,31.80,31.20,31.80,6534412,4.0,3196,205640129,0.05
110/04/12,32.80,33.00,31.50,31.65,17974759,5.0,8297,582321315,1.30
110/04/13,33.10,33.90,32.90,33.00,19428685,6.0,8886,648663414,0.30
110/04/14,32.65,33.75,32.15,33.45,17321091,7.0,7546,567666648,-0.45
110/04/15,35.90,35.90,33.05,33.20,47401791,8.0,16539,1679953018,3.25
110/04/16,39.45,39.45,36.70,37.65,58655442,9.0,25115,2261411408,3.55
110/04/19,40.10,42.00,39.55,40.20,54358138,10.0,26104,2211842509,0.65
110/04/20,39.95,39.95,38.65,39.70,25438337,11.0,12974,996242081,-0.15
110/04/21,40.60,41.85,40.45,41.20,27166257,12.0,13137,1114623054,0.65
110/04/22,38.00,41.30,37.25,41.20,31515475,13.0,14349,1237930564,-2.60
110/04/23,41.80,41.80,38.65,38.90,39528001,14.0,17436,1608205908,3.80
110/04/26,44.70,45.70,42.20,43.50,56775240,15.0,26557,2514325344,2.90
110/04/27,43.15,43.80,42.40,43.70,27144071,16.0,14058,1168599793,-1.55
110/04/28,43.10,45.60,42.45,42.85,32205386,17.0,15998,1417435212,-0.05
110/04/29,41.60,44.45,41.55,43.50,31620098,18.0,14110,1348635253,-1.50
110/03/02,28.60,29.40,28.50,29.35,4459974,NaN,2083,128747545,-0.40
110/03/03,29.30,29.40,28.70,28.80,6504698,NaN,3104,189697876,0.70
110/03/04,28.80,29.40,28.55,29.35,5408736,NaN,2760,156336282,-0.50
110/03/05,28.55,28.80,28.40,28.60,3087321,NaN,1643,88193924,-0.25
110/03/08,28.10,28.30,27.90,28.25,7208393,NaN,3741,202322795,-0.45
110/03/09,28.05,28.25,27.80,28.15,4557881,NaN,2213,127441639,-0.05
110/03/10,28.50,28.70,28.20,28.35,4368051,NaN,2397,124418898,0.45
110/03/11,29.00,29.20,28.60,28.70,7581121,NaN,3094,219355656,0.50
110/03/12,28.75,29.15,28.75,29.10,3309630,NaN,1644,95754802,-0.25
110/03/15,28.70,28.85,28.55,28.80,2510326,NaN,1517,71929279,-0.05
110/03/16,28.80,29.10,28.70,28.75,3559407,NaN,1699,102933450,0.10
...,...,...,...,...,...,...,...,...,...
110/07/13,37.40,38.70,35.95,38.15,9839483,NaN,4736,371287361,-0.40
110/07/14,36.60,38.00,36.55,38.00,6535919,NaN,3562,242192376,-0.80
110/07/15,38.05,38.20,36.60,36.95,6685363,NaN,3140,250502652,1.45
110/07/16,37.60,38.35,37.40,37.75,4768173,NaN,2179,180310714,-0.45
110/07/19,37.50,37.75,37.15,37.45,4098370,NaN,1929,153605230,-0.10
110/07/20,36.85,37.40,36.65,37.30,4724498,NaN,2604,174731372,-0.65
110/07/21,36.45,37.40,36.00,37.30,5618120,NaN,3043,205858806,-0.40
110/07/22,36.80,37.60,36.70,36.90,4876452,NaN,2588,180785431,0.35
110/07/23,37.20,38.00,36.90,37.50,6175220,NaN,2873,231180736,0.40
110/07/26,38.00,38.20,37.25,37.50,5654760,NaN,2636,213610518,0.80
110/07/27,36.75,38.20,36.75,38.15,5640698,NaN,2721,211075906,-1.25
110/07/28,35.35,37.05,35.05,36.85,7846468,NaN,4177,280456573,-1.40
110/07/29,37.90,38.30,36.00,36.00,10090739,NaN,5061,376113173,2.55
110/07/30,39.25,39.40,37.60,37.80,17934222,NaN,8322,695880247,1.35
110/08/02,39.95,40.40,39.25,39.40,13225018,NaN,6357,526012300,0.70
110/08/03,41.45,41.50,39.85,39.90,20068965,NaN,9677,819686694,1.50
110/08/04,41.55,42.10,40.90,41.50,13958962,NaN,6601,579516825,0.10
110/08/05,41.90,42.00,41.00,41.55,11327777,NaN,6044,471697770,0.35
110/08/06,40.35,42.30,40.30,41.80,11504106,NaN,5583,472491132,-1.55
110/08/09,38.60,39.80,38.50,39.00,11458664,NaN,5760,446584399,-1.75
110/08/10,38.90,39.60,38.65,39.15,5875318,NaN,2713,229644680,0.30
110/08/11,37.80,38.95,37.40,38.85,7297493,NaN,3585,278154579,-1.10
110/08/12,37.70,38.50,37.65,38.10,3649548,NaN,1864,138811811,-0.10
110/08/13,37.00,38.05,36.75,38.00,5510177,NaN,2726,205615558,-0.70
110/08/16,36.40,37.55,36.00,36.70,5759907,NaN,2957,210946325,-0.60
110/08/17,35.35,36.95,35.30,36.70,5983447,NaN,3342,215174727,-1.05
110/08/18,36.10,36.10,34.80,35.35,6200958,NaN,3278,220693400,0.75
110/08/19,34.65,35.85,34.50,35.70,6535352,NaN,3454,229438913,-1.45
110/08/20,34.65,35.55,34.25,34.95,4164011,NaN,2368,145199352,0.00
110/08/23,35.50,35.65,34.85,35.05,2728000,NaN,1397,96476450,0.85

In [23]:
import os
import pandas as pd
path = os.path.join('../../src/components/layouts/InfoTechCandlestickChart/price_data/price_1101.csv')
pd.read_csv(path)

,Date,Close,High,Low,Open,Unnamed: 0,Volume,成交筆數,成交金額,漲跌價差
0,110/03/02,42.10,42.50,42.10,42.25,0.0,21420625,6796,906927040,0.1
1,110/03/03,42.55,42.60,42.25,42.40,1.0,18135047,5415,769759407,0.45
2,110/03/04,42.50,42.55,42.15,42.55,2.0,19801467,6972,838685338,-0.05
3,110/03/05,42.50,42.50,42.05,42.15,3.0,9262307,3296,392707343,0.0
4,110/03/08,42.65,42.90,42.55,42.60,4.0,29090035,5849,1178550422,0.15
5,110/03/09,43.40,43.40,42.80,42.90,5.0,24736825,11262,1065107252,0.75
6,110/03/10,43.00,43.40,42.90,43.40,6.0,23663072,10925,1018547236,-0.4
7,110/03/11,42.85,43.20,42.85,43.15,7.0,22296062,8472,958151923,-0.15
8,110/03/12,42.70,42.85,42.55,42.80,8.0,18550910,8663,791480365,-0.15
9,110/03/15,42.35,42.75,42.30,42.70,9.0,24555341,12410,1043325517,-0.35
10,110/03/16,42.60,42.70,42.35,42.40,10.0,10741370,4876,457117591,0.25
11,110/03/17,42.85,42.95,42.65,42.70,11.0,12653419,6625,542051941,0.25
12,110/03/18,43.10,43.25,42.90,42.90,12.0,14889159,6539,641451149,0.25
13,110/03/19,42.70,43.00,42.60,43.00,13.0,23488235,6968,1004044763,-0.4
14,110/03/22,45.80,46.90,45.05,46.85,14.0,102000789,42072,4674290576,3.1
15,110/03/23,45.70,46.00,45.60,46.00,15.0,38751832,15253,1773398488,-0.1
16,110/03/24,45.55,45.75,45.50,45.70,16.0,21118254,9483,962980283,-0.15
17,110/03/25,45.55,45.65,45.35,45.55,17.0,23439316,9509,1066131621,0.0
18,110/03/26,46.15,46.25,45.60,45.60,18.0,39771169,14731,1831556508,0.6
19,110/03/29,46.50,46.60,46.20,46.45,19.0,31037275,11788,1441000335,0.35
20,110/03/30,46.55,46.60,46.25,46.50,20.0,34184434,8354,1587363402,0.05
21,110/03/31,46.80,46.80,46.55,46.60,21.0,21882853,8822,1022451932,0.25
22,110/04/01,46.70,46.95,46.60,46.85,NaN,16542110,7051,772765655,-0.1
23,110/04/06,46.85,46.95,46.60,46.85,NaN,33845298,13638,1584212660,0.15
24,110/04/07,46.80,46.85,46.70,46.80,NaN,12964742,5953,606582722,-0.05
25,110/04/08,46.90,46.90,46.60,46.70,NaN,16095270,7734,753019406,0.1
26,110/04/09,46.70,47.05,46.70,46.90,NaN,19693919,9966,922360423,-0.2
27,110/04/12,46.85,46.85,46.70,46.70,NaN,18150925,7261,849423889,0.15
28,110/04/13,47.20,47.50,46.85,46.90,NaN,31772378,14139,1500852046,0.35
29,110/04/14,47.00,47.30,46.60,47.25,NaN,26957007,11132,1265737458,-0.2
...,...,...,...,...,...,...,...,...,...,...
90,110/07/12,52.20,52.40,51.80,52.20,NaN,26725789,10097,1390815526,0.2
91,110/07/13,51.90,52.50,51.70,52.50,NaN,23392966,9927,1217373151,-0.3
92,110/07/14,51.50,52.00,51.30,51.90,NaN,20343534,8784,1047180343,-0.4
93,110/07/15,51.60,51.80,51.30,51.50,NaN,11938157,5094,615005211,0.1
94,110/07/16,51.50,51.60,51.30,51.50,NaN,12188101,5958,627236112,-0.1
95,110/07/19,52.00,52.00,51.30,51.40,NaN,11286149,4773,583396825,0.5
96,110/07/20,51.70,51.80,51.40,51.60,NaN,10145510,4446,523710103,-0.3
97,110/07/21,51.80,52.40,51.70,52.00,NaN,24843451,10518,1291868626,0.1
98,110/07/22,52.10,52.30,51.90,52.30,NaN,16553240,7073,861904218,0.3
99,110/07/23,53.00,53.10,52.20,52.30,NaN,34420099,13742,1813726922,0.9
100,110/07/26,53.20,53.80,53.00,53.40,NaN,24737557,10862,1320028119,0.2
101,110/07/27,53.00,53.30,52.60,53.30,NaN,18654939,8187,986141697,-0.2
102,110/07/28,52.40,53.00,52.00,52.80,NaN,36454371,13822,1908346074,-0.6
103,110/07/29,52.90,52.90,52.10,52.50,NaN,18957983,7236,995989067,0.5
104,110/07/30,52.60,52.90,52.50,52.90,NaN,12473682,5158,657537327,-0.3
105,110/08/02,52.80,52.80,52.50,52.70,NaN,14023385,6962,738635946,+0.20
106,110/08/03,53.90,53.90,53.00,53.10,NaN,45545154,16031,2441886377,+1.10
107,110/08/04,53.80,54.50,53.60,54.20,NaN,23552465,9940,1271178027,-0.10
108,110/08/05,52.70,53.80,52.60,53.80,NaN,38673195,14252,2050224696,-1.10
109,110/08/06,52.90,53.20,52.40,53.20,NaN,32500825,9306,1714404302,+0.20
110,110/08/09,52.40,52.60,51.70,52.60,NaN,33630358,11333,1755733056,-0.50
111,110/08/10,51.90,52.40,51.70,52.20,NaN,34313716,11543,1780541159,-0.50
112,110/08/11,51.10,51.70,50.80,51.60,NaN,59669569,24883,3049740724,-0.80
113,110/08/12,47.60,47.75,45.65,45.85,NaN,87897408,30427,4140954924,X0.00
114,110/08/13,48.40,48.60,47.95,48.05,NaN,23823791,12761,1150516862,+0.80
115,110/08/16,47.95,48.45,47.70,48.40,NaN,26728439,12279,1281549042,-0.45
116,110/08/17,47.30,47.95,47.20,47.95,NaN,25544445,11718,1211673397,-0.65
117,110/08/18,47.25,47.30,46.40,46.90,NaN,25211046,12379,1181293068,-0.05
118,110/08/19,46.20,47.25,46.00,47.25,NaN,26172172,17217,1215272787,-1.05
119,110/08/20,46.15,46.75,45.70,45.90,NaN,19229307,9518,889143439,-0.05

In [47]:
import sqlite3
conn = sqlite3.connect('price.db')
sql_table = pd.read_sql('select * from price_1101', conn)
# sql_table = sql_table.set_index('Date')
sql_table

,index,Date,Volume,成交金額,Open,High,Low,Close,漲跌價差,成交筆數
0,0,110/04/01,16542110,772765655,46.85,46.95,46.60,46.70,-0.10,7051
1,1,110/04/06,33845298,1584212660,46.85,46.95,46.60,46.85,0.15,13638
2,2,110/04/07,12964742,606582722,46.80,46.85,46.70,46.80,-0.05,5953
3,3,110/04/08,16095270,753019406,46.70,46.90,46.60,46.90,0.10,7734
4,4,110/04/09,19693919,922360423,46.90,47.05,46.70,46.70,-0.20,9966
5,5,110/04/12,18150925,849423889,46.70,46.85,46.70,46.85,0.15,7261
6,6,110/04/13,31772378,1500852046,46.90,47.50,46.85,47.20,0.35,14139
7,7,110/04/14,26957007,1265737458,47.25,47.30,46.60,47.00,-0.20,11132
8,8,110/04/15,39227693,1880939840,47.05,48.50,47.00,47.90,0.90,14647
9,9,110/04/16,54142060,2622752960,47.90,49.00,47.75,49.00,1.10,19206
10,10,110/04/19,61427913,3074242573,49.90,50.50,49.75,50.40,1.40,27163
11,11,110/04/20,93792314,4926535026,53.10,54.90,51.10,52.00,1.60,42840
12,12,110/04/21,139647984,7594206791,52.20,56.90,52.10,55.70,3.70,58872
13,13,110/04/22,204668299,11590653736,57.10,58.70,53.50,54.10,-1.60,82759
14,14,110/04/23,105526229,5547615744,53.70,53.80,51.10,53.00,-1.10,45023
15,15,110/04/26,79418607,4226623533,53.40,54.20,52.10,53.10,0.10,35187
16,16,110/04/27,41576962,2191107853,53.20,53.20,52.50,52.70,-0.40,20636
17,17,110/04/28,42357712,2225015075,52.70,53.20,52.10,53.20,0.50,19766
18,18,110/04/29,44585563,2336765438,53.00,53.10,52.10,52.10,-1.10,21163

In [37]:
import requests
import pandas as pd

date = 20210401
stockid = 1101

url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=html&date=' + str(date) + '&stockNo=' + str(stockid)
data = pd.read_html(requests.get(url).text)[0]
data.columns = data.columns.droplevel(0)
data = data.rename(columns={'日期': 'Date', '成交股數': 'Volume', '開盤價': 'Open', '最高價': 'High', '最低價': 'Low', '收盤價': 'Close'})

In [48]:
sql_table.append(data)

,Close,Date,High,Low,Open,Volume,index,成交筆數,成交金額,漲跌價差
0,46.70,110/04/01,46.95,46.60,46.85,16542110,0.0,7051,772765655,-0.10
1,46.85,110/04/06,46.95,46.60,46.85,33845298,1.0,13638,1584212660,0.15
2,46.80,110/04/07,46.85,46.70,46.80,12964742,2.0,5953,606582722,-0.05
3,46.90,110/04/08,46.90,46.60,46.70,16095270,3.0,7734,753019406,0.10
4,46.70,110/04/09,47.05,46.70,46.90,19693919,4.0,9966,922360423,-0.20
5,46.85,110/04/12,46.85,46.70,46.70,18150925,5.0,7261,849423889,0.15
6,47.20,110/04/13,47.50,46.85,46.90,31772378,6.0,14139,1500852046,0.35
7,47.00,110/04/14,47.30,46.60,47.25,26957007,7.0,11132,1265737458,-0.20
8,47.90,110/04/15,48.50,47.00,47.05,39227693,8.0,14647,1880939840,0.90
9,49.00,110/04/16,49.00,47.75,47.90,54142060,9.0,19206,2622752960,1.10
10,50.40,110/04/19,50.50,49.75,49.90,61427913,10.0,27163,3074242573,1.40
11,52.00,110/04/20,54.90,51.10,53.10,93792314,11.0,42840,4926535026,1.60
12,55.70,110/04/21,56.90,52.10,52.20,139647984,12.0,58872,7594206791,3.70
13,54.10,110/04/22,58.70,53.50,57.10,204668299,13.0,82759,11590653736,-1.60
14,53.00,110/04/23,53.80,51.10,53.70,105526229,14.0,45023,5547615744,-1.10
15,53.10,110/04/26,54.20,52.10,53.40,79418607,15.0,35187,4226623533,0.10
16,52.70,110/04/27,53.20,52.50,53.20,41576962,16.0,20636,2191107853,-0.40
17,53.20,110/04/28,53.20,52.10,52.70,42357712,17.0,19766,2225015075,0.50
18,52.10,110/04/29,53.10,52.10,53.00,44585563,18.0,21163,2336765438,-1.10
0,46.70,110/04/01,46.95,46.60,46.85,16542110,NaN,7051,772765655,-0.10
1,46.85,110/04/06,46.95,46.60,46.85,33845298,NaN,13638,1584212660,0.15
2,46.80,110/04/07,46.85,46.70,46.80,12964742,NaN,5953,606582722,-0.05
3,46.90,110/04/08,46.90,46.60,46.70,16095270,NaN,7734,753019406,0.10
4,46.70,110/04/09,47.05,46.70,46.90,19693919,NaN,9966,922360423,-0.20
5,46.85,110/04/12,46.85,46.70,46.70,18150925,NaN,7261,849423889,0.15
6,47.20,110/04/13,47.50,46.85,46.90,31772378,NaN,14139,1500852046,0.35
7,47.00,110/04/14,47.30,46.60,47.25,26957007,NaN,11132,1265737458,-0.20
8,47.90,110/04/15,48.50,47.00,47.05,39227693,NaN,14647,1880939840,0.90
9,49.00,110/04/16,49.00,47.75,47.90,54142060,NaN,19206,2622752960,1.10
10,50.40,110/04/19,50.50,49.75,49.90,61427913,NaN,27163,3074242573,1.40
11,52.00,110/04/20,54.90,51.10,53.10,93792314,NaN,42840,4926535026,1.60
12,55.70,110/04/21,56.90,52.10,52.20,139647984,NaN,58872,7594206791,3.70
13,54.10,110/04/22,58.70,53.50,57.10,204668299,NaN,82759,11590653736,-1.60
14,53.00,110/04/23,53.80,51.10,53.70,105526229,NaN,45023,5547615744,-1.10
15,53.10,110/04/26,54.20,52.10,53.40,79418607,NaN,35187,4226623533,0.10
16,52.70,110/04/27,53.20,52.50,53.20,41576962,NaN,20636,2191107853,-0.40
17,53.20,110/04/28,53.20,52.10,52.70,42357712,NaN,19766,2225015075,0.50
18,52.10,110/04/29,53.10,52.10,53.00,44585563,NaN,21163,2336765438,-1.10